local rude = require('rude.init')
local Engine = require('rude.Engine')

describe('init module: ', function()
    it('returns a new Engine instance when called', function()
        assert.is.instanceOf(rude(), Engine)
    end)
    it('exposes DataContext class', function()
        assert.is.equal(rude.DataContext, require('rude.DataContext'))
    end)
    it('exposes Engine class', function()
        assert.is.equal(rude.Engine, require('rude.Engine'))
    end)
    it('exposes Exception class', function()
        assert.is.equal(rude.Exception, require('rude.Exception'))
    end)
    it('exposes log module', function()
        assert.is.equal(rude.log, require('rude.log'))
    end)
    it('exposes MissingComClassException class', function()
        assert.is.equal(rude.MissingComClassException, require('rude.MissingComClassException'))
    end)
    it('exposes MissingComException class', function()
        assert.is.equal(rude.MissingComException, require('rude.MissingComException'))
    end)
    it('exposes PoolableMixin', function()
        assert.is.equal(rude.PoolableMixin, require('rude.PoolableMixin'))
    end)
    it('exposes RudeObject class', function()
        assert.is.equal(rude.RudeObject, require('rude.RudeObject'))
    end)
    it('exposes Scene class', function()
        assert.is.equal(rude.Scene, require('rude.Scene'))
    end)
    it('exposes Sys class', function()
        assert.is.equal(rude.Sys, require('rude.Sys'))
    end)
    it('exposes TablePool class', function()
        assert.is.equal(rude.TablePool, require('rude.TablePool'))
    end)
    it('exposes util module', function()
        assert.is.equal(rude.util, require('rude.util'))
    end)
    it('exposes bitserPlugin', function()
        assert.is.equal(rude.plugins.bitserPlugin, require('rude.plugins.bitserPlugin'))
    end)
    it('exposes dkjsonPlugin', function()
        assert.is.equal(rude.plugins.dkjsonPlugin, require('rude.plugins.dkjsonPlugin'))
    end)
    it('exposes lovePlugin', function()
        assert.is.equal(rude.plugins.lovePlugin, require('rude.plugins.lovePlugin'))
    end)
    it('exposes stdPlugin', function()
        assert.is.equal(rude.plugins.stdPlugin, require('rude.plugins.stdPlugin'))
    end)
end)