local rude = require('rude.init')
local Engine = require('rude.Engine')

describe('init module: ', function()
    it('returns a new Engine instance when called', function()
        assert.is.instanceOf(rude(), Engine)
    end)
    it('exposes all public modules', function()
        assert.is.equal(rude.Engine, require('rude.Engine'))
        assert.is.equal(rude.EventEmitterMixin, require('rude.EventEmitterMixin'))
        assert.is.equal(rude.PoolableMixin, require('rude.PoolableMixin'))
        assert.is.equal(rude.RudeObject, require('rude.RudeObject'))
        assert.is.equal(rude.Scene, require('rude.Scene'))
        assert.is.equal(rude.Sys, require('rude.Sys'))
        assert.is.equal(rude.TablePool, require('rude.TablePool'))
        assert.is.equal(rude.util, require('rude.util'))
    end)
end)