local RudeObject = require('rude.RudeObject')

describe('a RudeObject instance', function()
    describe('initialize()', function()
        it('returns the instance', function()
            local o = RudeObject()
            assert.is.equal(o, o:initialize())
        end)
    end)

    describe('validate()', function()
        it('returns true', function()
            assert.is.True(RudeObject():validate())
        end)
    end)

    describe('destroy()', function()
        it('does not error', function()
            assert.has_no.errors(function()
                RudeObject():destroy()
            end)
        end)
    end)
end)